
version: 2
jobs:
  build:
    docker:
      - image: amd64/ubuntu
    steps: 
      - run:
            name: apt update
            command: apt-get update
      - run:
            name: apt install
            command: |
              apt-get install -y \
                                  git \
                                  git-lfs \
                                  sudo \
                                  avr-libc \
                                  avrdude \
                                  build-essential \
                                  bison \
                                  ccache \
                                  curl \
                                  dosfstools \
                                  flashrom \
                                  flex \
                                  gcc-avr \
                                  git-lfs \
                                  gnat \
                                  libncurses-dev \
                                  mtools \
                                  nasm \
                                  parted \
                                  python \
                                  python3-distutils \
                                  sdcc \
                                  uuid-dev \
                                  zlib1g-dev
      - run:
            name: git clone
            command: |
              git clone https://github.com/system76/firmware-open.git
      - run:
            name: cd
            command: cd firmware-open

      - run:
          name: deps.sh
          command: |
            ./firmware-open/scripts/deps.sh
      - run:
            name: build qemu
            command: |
              ./firmware-open/scripts/build.sh qemu


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
